AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  app

  Sample SAM Template for app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  AppStage:
    Type: String
    Default: api
    Description: API Gateway Stage, used as a prefix for the endpoint URLs
    AllowedPattern: ^[A-Za-z]+$
    MaxLength: 10
    MinLength: 1
    ConstraintDescription: "1-10 Latin letters"

Resources:
  # explicitly create API Gateway, rather than auto-create
  # create custom stage using global AppStage parameter
  WebApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref AppStage
  # S3 Bucket to persist information
  UploadS3Bucket:
    Type: AWS::S3::Bucket
  ShowFormFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: user-form/
      Handler: show-form.lambdaHandler
      Runtime: nodejs12.x
      # AutoPublishAlias: live
      Events:
        ShowForm:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref WebApi
  ProcessFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user-form/
      Handler: process-form.lambdaHandler
      Runtime: nodejs12.x    
      Events:  
        SubmitForm:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: post
            RestApiId: !Ref WebApi
      Environment:
        Variables:
          UPLOAD_S3_BUCKET: !Ref UploadS3Bucket
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref UploadS3Bucket

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UserFormApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${WebApi}.execute-api.${AWS::Region}.amazonaws.com/${AppStage}/"
  ShowFormFunction:
    Description: "Show Form Lambda Function ARN"
    Value: !GetAtt ShowFormFunction.Arn
  ShowFormFunctionIamRole:
    Description: "Implicit IAM Role created for ShowForm function"
    Value: !GetAtt ShowFormFunctionRole.Arn
  ProcessFormFunction:
    Description: "Process Form Lambda Function ARN"
    Value: !GetAtt ProcessFormFunction.Arn
  ProcessFormFunctionIamRole:
    Description: "Implicit IAM Role created for ProcessForm function"
    Value: !GetAtt ProcessFormFunctionRole.Arn
  uploadBucket:
    Description: "S3 Bucket for user information"
    Value: !Ref UploadS3Bucket
